### ISSUE TITLE
Checkout Flow (AudioTroupe Side)

### ISSUE THREAD

**Issue by devenrl** [priolkar2010/audiotroupe#16]
- Checkout Page (UI Complete)
- Order Review on the Checkout Page (UI Pending/Data Binding Pending)
- Checkout Form submission to Stripe
- Success Redirect to Order Confirmation Summary page
- Error Display on the Checkout Page Itself

**Comment by priolkar2010** [comment]
everything except the error is done. can we make the Error another issue?
